package de.example.reports.database;
import com.zaxxer.hikari.HikariConfig; import com.zaxxer.hikari.HikariDataSource; import de.example.reports.model.*; import java.io.File; import java.sql.*; import java.time.Instant; import java.util.*; import java.util.concurrent.*;
public final class Database implements AutoCloseable {
 private final HikariDataSource dataSource; private final ExecutorService executor;
 public Database(File file) { HikariConfig c=new HikariConfig(); c.setJdbcUrl("jdbc:sqlite:"+file.getAbsolutePath()); c.setMaximumPoolSize(1); c.setPoolName("Reports-SQLite"); c.setConnectionTestQuery("SELECT 1"); dataSource=new HikariDataSource(c); executor=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"Reports-Database");t.setDaemon(true);return t;}); initialize(); }
 private void initialize(){ try(Connection c=dataSource.getConnection(); Statement s=c.createStatement()){s.executeUpdate("PRAGMA journal_mode=WAL");s.executeUpdate("CREATE TABLE IF NOT EXISTS known_players (uuid TEXT PRIMARY KEY, name TEXT NOT NULL, first_seen INTEGER NOT NULL, last_seen INTEGER NOT NULL)");s.executeUpdate("CREATE TABLE IF NOT EXISTS reports (id INTEGER PRIMARY KEY AUTOINCREMENT, reported_player_uuid TEXT NOT NULL, reported_player_name TEXT NOT NULL, reporter_uuid TEXT NOT NULL, reporter_name TEXT NOT NULL, reason TEXT NOT NULL, timestamp INTEGER NOT NULL, status TEXT NOT NULL, grim_flags TEXT NOT NULL)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_reports_reported_uuid ON reports(reported_player_uuid)");s.executeUpdate("CREATE TABLE IF NOT EXISTS discord_chat_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, channel_name TEXT NOT NULL, author_id TEXT NOT NULL, author_name TEXT NOT NULL, message TEXT NOT NULL, timestamp INTEGER NOT NULL)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_chat_logs_timestamp ON discord_chat_logs(timestamp DESC)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_chat_logs_author ON discord_chat_logs(author_name)");s.executeUpdate("CREATE TABLE IF NOT EXISTS sanctions (player_uuid TEXT NOT NULL, player_name TEXT NOT NULL, type TEXT NOT NULL, expires_at INTEGER, reason TEXT NOT NULL, PRIMARY KEY(player_uuid,type))");}catch(SQLException e){throw new IllegalStateException("Could not initialize SQLite",e);} }
 public CompletableFuture<Void> saveChatLog(String guildId,String channelId,String channelName,String authorId,String authorName,String message,long timestamp){return async(()->{try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO discord_chat_logs(guild_id,channel_id,channel_name,author_id,author_name,message,timestamp) VALUES(?,?,?,?,?,?,?)")){p.setString(1,guildId);p.setString(2,channelId);p.setString(3,channelName);p.setString(4,authorId);p.setString(5,authorName);p.setString(6,message);p.setLong(7,timestamp);p.executeUpdate();return null;}});}
 public CompletableFuture<List<String>> chatLogs(String guildId,String player,String text,boolean commandsOnly,int limit){return async(()->{StringBuilder sql=new StringBuilder("SELECT channel_name,author_name,message,timestamp FROM discord_chat_logs WHERE guild_id=?");List<String> parameters=new ArrayList<>();parameters.add(guildId);if(player!=null&&!player.isBlank()){sql.append(" AND lower(author_name) LIKE lower(?)");parameters.add("%"+player+"%");}if(text!=null&&!text.isBlank()){sql.append(" AND lower(message) LIKE lower(?)");parameters.add("%"+text+"%");}if(commandsOnly)sql.append(" AND message LIKE '!%'");sql.append(" ORDER BY timestamp DESC LIMIT ?");try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement(sql.toString())){for(int i=0;i<parameters.size();i++)p.setString(i+1,parameters.get(i));p.setInt(parameters.size()+1,limit);try(ResultSet r=p.executeQuery()){List<String> result=new ArrayList<>();while(r.next())result.add("["+r.getString("channel_name")+"] "+r.getString("author_name")+": "+r.getString("message"));return result;}}});}
 public CompletableFuture<Void> upsertPlayer(UUID id,String name){return async(()->{long now=System.currentTimeMillis();try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO known_players(uuid,name,first_seen,last_seen) VALUES(?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET name=excluded.name,last_seen=excluded.last_seen")){p.setString(1,id.toString());p.setString(2,name);p.setLong(3,now);p.setLong(4,now);p.executeUpdate();return null;}});}
 public CompletableFuture<List<KnownPlayer>> players(String query){return async(()->{String sql="SELECT * FROM known_players WHERE lower(name) LIKE lower(?) ORDER BY name LIMIT 500";try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,"%"+query+"%");try(ResultSet r=p.executeQuery()){List<KnownPlayer> list=new ArrayList<>();while(r.next())list.add(player(r));return list;}}});}
 public CompletableFuture<Optional<KnownPlayer>> playerByName(String name){return async(()->{try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM known_players WHERE lower(name)=lower(?) LIMIT 1")){p.setString(1,name);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(player(r)):Optional.empty();}}});}
 public CompletableFuture<Report> create(UUID target,String targetName,UUID reporter,String reporterName,String reason,String flags){return async(()->{long now=System.currentTimeMillis();String sql="INSERT INTO reports(reported_player_uuid,reported_player_name,reporter_uuid,reporter_name,reason,timestamp,status,grim_flags) VALUES(?,?,?,?,?,?,?,?)";try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS)){p.setString(1,target.toString());p.setString(2,targetName);p.setString(3,reporter.toString());p.setString(4,reporterName);p.setString(5,reason);p.setLong(6,now);p.setString(7,ReportStatus.OPEN.name());p.setString(8,flags);p.executeUpdate();try(ResultSet k=p.getGeneratedKeys()){if(!k.next())throw new SQLException("No report id returned");return new Report(k.getLong(1),target,targetName,reporter,reporterName,reason,Instant.ofEpochMilli(now),ReportStatus.OPEN,flags);}}});}
 public CompletableFuture<Optional<Report>> report(long id){return async(()->{try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM reports WHERE id=?")){p.setLong(1,id);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(report(r)):Optional.empty();}}});}
 public CompletableFuture<List<Report>> reportsFor(UUID target){return async(()->{try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM reports WHERE reported_player_uuid=? ORDER BY timestamp DESC LIMIT 25")){p.setString(1,target.toString());try(ResultSet r=p.executeQuery()){List<Report> a=new ArrayList<>();while(r.next())a.add(report(r));return a;}}});}
 public CompletableFuture<Boolean> updateStatus(long id,ReportStatus status){return async(()->{try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement("UPDATE reports SET status=? WHERE id=?")){p.setString(1,status.name());p.setLong(2,id);return p.executeUpdate()==1;}});}
 public CompletableFuture<List<Report>> recentReports(ReportStatus filter,int offset,int limit){return async(()->{String sql=filter==null?"SELECT * FROM reports ORDER BY timestamp DESC LIMIT ? OFFSET ?":"SELECT * FROM reports WHERE status=? ORDER BY timestamp DESC LIMIT ? OFFSET ?";try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement(sql)){int i=1;if(filter!=null)p.setString(i++,filter.name());p.setInt(i++,limit);p.setInt(i,offset);try(ResultSet r=p.executeQuery()){List<Report> reports=new ArrayList<>();while(r.next())reports.add(report(r));return reports;}}});}
 public CompletableFuture<Integer> reportCount(ReportStatus filter){return async(()->{String sql=filter==null?"SELECT COUNT(*) FROM reports":"SELECT COUNT(*) FROM reports WHERE status=?";try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement(sql)){if(filter!=null)p.setString(1,filter.name());try(ResultSet r=p.executeQuery()){return r.next()?r.getInt(1):0;}}});}
 public CompletableFuture<Void> sanction(UUID uuid,String name,Sanction.Type type,Instant expiresAt,String reason){return async(()->{try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO sanctions(player_uuid,player_name,type,expires_at,reason) VALUES(?,?,?,?,?) ON CONFLICT(player_uuid,type) DO UPDATE SET player_name=excluded.player_name,expires_at=excluded.expires_at,reason=excluded.reason")){p.setString(1,uuid.toString());p.setString(2,name);p.setString(3,type.name());if(expiresAt==null)p.setNull(4,Types.BIGINT);else p.setLong(4,expiresAt.toEpochMilli());p.setString(5,reason);p.executeUpdate();return null;}});}
 public CompletableFuture<Optional<Sanction>> sanction(UUID uuid,Sanction.Type type){return async(()->{try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement("SELECT * FROM sanctions WHERE player_uuid=? AND type=?")){p.setString(1,uuid.toString());p.setString(2,type.name());try(ResultSet r=p.executeQuery()){if(!r.next())return Optional.empty();long expiry=r.getLong("expires_at");Instant until=r.wasNull()?null:Instant.ofEpochMilli(expiry);Sanction sanction=new Sanction(uuid,r.getString("player_name"),type,until,r.getString("reason"));if(!sanction.active()){try(PreparedStatement delete=c.prepareStatement("DELETE FROM sanctions WHERE player_uuid=? AND type=?")){delete.setString(1,uuid.toString());delete.setString(2,type.name());delete.executeUpdate();}return Optional.empty();}return Optional.of(sanction);}}});}
 public CompletableFuture<Void> removeSanction(UUID uuid,Sanction.Type type){return async(()->{try(Connection c=dataSource.getConnection();PreparedStatement p=c.prepareStatement("DELETE FROM sanctions WHERE player_uuid=? AND type=?")){p.setString(1,uuid.toString());p.setString(2,type.name());p.executeUpdate();return null;}});}
 private KnownPlayer player(ResultSet r)throws SQLException{return new KnownPlayer(UUID.fromString(r.getString("uuid")),r.getString("name"),Instant.ofEpochMilli(r.getLong("first_seen")),Instant.ofEpochMilli(r.getLong("last_seen")));}
 private Report report(ResultSet r)throws SQLException{return new Report(r.getLong("id"),UUID.fromString(r.getString("reported_player_uuid")),r.getString("reported_player_name"),UUID.fromString(r.getString("reporter_uuid")),r.getString("reporter_name"),r.getString("reason"),Instant.ofEpochMilli(r.getLong("timestamp")),ReportStatus.valueOf(r.getString("status")),r.getString("grim_flags"));}
 private <T> CompletableFuture<T> async(Callable<T> task){return CompletableFuture.supplyAsync(()->{try{return task.call();}catch(Exception e){throw new CompletionException(e);}},executor);} public void close(){executor.shutdown();dataSource.close();}
}
