package de.example.reports.gui;

import de.example.reports.database.Database;
import de.example.reports.model.*;
import de.example.reports.moderation.ModerationService;
import net.kyori.adventure.text.Component;
import org.bukkit.*;
import org.bukkit.entity.Player;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.java.JavaPlugin;
import java.time.ZoneId;
import java.time.Duration;
import java.time.format.DateTimeFormatter;
import java.util.*;

/** Staff-facing report management GUI. */
public final class AdminReportGuiService {
 private static final int PAGE_SIZE=45;
 private static final DateTimeFormatter TIME=DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm").withZone(ZoneId.of("Europe/Berlin"));
 private final JavaPlugin plugin; private final Database database; private final ModerationService moderation;
 public AdminReportGuiService(JavaPlugin plugin,Database database,ModerationService moderation){this.plugin=plugin;this.database=database;this.moderation=moderation;}
 public void open(Player player){loadList(player,0,null);}
 private void loadList(Player player,int requested,ReportStatus filter){database.reportCount(filter).thenCombine(database.recentReports(filter,Math.max(0,requested)*PAGE_SIZE,PAGE_SIZE),(count,reports)->new Object[]{count,reports}).thenAccept(result->plugin.getServer().getScheduler().runTask(plugin,()->{int count=(Integer)result[0];@SuppressWarnings("unchecked") List<Report> reports=(List<Report>)result[1];int pages=Math.max(1,(int)Math.ceil((double)count/PAGE_SIZE));renderList(player,Math.min(Math.max(0,requested),pages-1),pages,filter,reports);}));}
 private void renderList(Player player,int page,int pages,ReportStatus filter,List<Report> reports){AdminReportInventory holder=AdminReportInventory.list(page,filter,reports.stream().map(Report::id).toList());Inventory inv=Bukkit.createInventory(holder,54,Component.text("Reports – Verwaltung"));holder.inventory(inv);for(int i=45;i<54;i++)inv.setItem(i,item(Material.GRAY_STAINED_GLASS_PANE," ",List.of()));for(int i=0;i<reports.size();i++){Report r=reports.get(i);inv.setItem(i,item(statusMaterial(r.status()),statusColor(r.status())+"#"+r.id()+" §f"+r.reportedName(),List.of("§7Von: §f"+r.reporterName(),"§7Status: "+statusColor(r.status())+r.status(),"§7Zeit: §f"+TIME.format(r.timestamp()),"§8Klicken für Details")));}inv.setItem(45,item(Material.HOPPER,"§eFilter: §f"+(filter==null?"Alle":filter),List.of("§7Klicken zum Wechseln")));inv.setItem(49,item(Material.BARRIER,"§cSchließen",List.of()));inv.setItem(53,item(Material.PAPER,"§bSeite "+(page+1)+"/"+pages,List.of("§7"+reports.size()+" Einträge auf dieser Seite")));if(page>0)inv.setItem(48,item(Material.ARROW,"§eZurück",List.of()));if(page+1<pages)inv.setItem(50,item(Material.ARROW,"§eWeiter",List.of()));player.openInventory(inv);}
 public void click(Player player,AdminReportInventory holder,int slot,boolean rightClick){if(holder.view()==AdminReportInventory.View.LIST){if(slot==45){loadList(player,0,next(holder.filter()));return;}if(slot==48){loadList(player,holder.page()-1,holder.filter());return;}if(slot==50){loadList(player,holder.page()+1,holder.filter());return;}if(slot==49){player.closeInventory();return;}if(slot>=0&&slot<holder.reportIds().size())openDetail(player,holder.reportIds().get(slot),holder.page(),holder.filter());return;}if(slot==49){loadList(player,holder.page(),holder.filter());return;}if(slot>=45&&slot<=48){if(!player.hasPermission("reports.manage")){player.sendMessage("§cDafür hast du keine Berechtigung.");return;}ReportStatus[] statuses={ReportStatus.OPEN,ReportStatus.REVIEWING,ReportStatus.RESOLVED,ReportStatus.REJECTED};database.updateStatus(holder.reportId(),statuses[slot-45]).thenAccept(ok->plugin.getServer().getScheduler().runTask(plugin,()->openDetail(player,holder.reportId(),holder.page(),holder.filter(),holder.tempBanIndex(),holder.tempMuteIndex())));return;}if((slot==36&&player.hasPermission("reports.tempban"))||(slot==38&&player.hasPermission("reports.tempmute"))){if(rightClick){openDetail(player,holder.reportId(),holder.page(),holder.filter(),slot==36?(holder.tempBanIndex()+1)%4:holder.tempBanIndex(),slot==38?(holder.tempMuteIndex()+1)%4:holder.tempMuteIndex());return;}database.report(holder.reportId()).thenAccept(report->report.ifPresent(value->applyModeration(player,value,slot,holder)));return;}if((slot==37&&player.hasPermission("reports.ban"))||(slot==39&&player.hasPermission("reports.mute"))||(slot==40&&player.hasPermission("reports.unban")))database.report(holder.reportId()).thenAccept(report->report.ifPresent(value->applyModeration(player,value,slot,holder)));}
 private void applyModeration(Player staff,Report report,int slot,AdminReportInventory holder){Duration[] bans={Duration.ofHours(1),Duration.ofDays(1),Duration.ofDays(7),Duration.ofDays(30)};Duration[] mutes={Duration.ofMinutes(30),Duration.ofHours(6),Duration.ofDays(1),Duration.ofDays(7)};switch(slot){case 36->moderation.apply(staff,report.reportedUuid(),report.reportedName(),Sanction.Type.BAN,bans[holder.tempBanIndex()],"Report #"+report.id()+": "+report.reason());case 37->moderation.apply(staff,report.reportedUuid(),report.reportedName(),Sanction.Type.BAN,null,"Report #"+report.id()+": "+report.reason());case 38->moderation.apply(staff,report.reportedUuid(),report.reportedName(),Sanction.Type.MUTE,mutes[holder.tempMuteIndex()],"Report #"+report.id()+": "+report.reason());case 39->moderation.apply(staff,report.reportedUuid(),report.reportedName(),Sanction.Type.MUTE,null,"Report #"+report.id()+": "+report.reason());case 40->moderation.pardon(staff,report.reportedUuid(),report.reportedName());default->{} }plugin.getServer().getScheduler().runTaskLater(plugin,()->openDetail(staff,report.id(),holder.page(),holder.filter(),holder.tempBanIndex(),holder.tempMuteIndex()),10L);}
 private void openDetail(Player player,long id,int page,ReportStatus filter){openDetail(player,id,page,filter,2,2);} private void openDetail(Player player,long id,int page,ReportStatus filter,int banIndex,int muteIndex){database.report(id).thenAccept(optional->plugin.getServer().getScheduler().runTask(plugin,()->{if(optional.isEmpty()){player.sendMessage("§cReport #"+id+" wurde nicht gefunden.");loadList(player,page,filter);return;}renderDetail(player,optional.get(),page,filter,banIndex,muteIndex);}));}
 private void renderDetail(Player player,Report report,int page,ReportStatus filter,int banIndex,int muteIndex){AdminReportInventory holder=AdminReportInventory.detail(report.id(),page,filter,banIndex,muteIndex);Inventory inv=Bukkit.createInventory(holder,54,Component.text("Report #"+report.id()));holder.inventory(inv);for(int i=0;i<54;i++)inv.setItem(i,item(Material.GRAY_STAINED_GLASS_PANE," ",List.of()));inv.setItem(13,item(statusMaterial(report.status()),statusColor(report.status())+"Report #"+report.id(),List.of("§7Status: "+statusColor(report.status())+report.status(),"§7Zeit: §f"+TIME.format(report.timestamp()))));inv.setItem(20,head(report.reportedUuid(),report.reportedName(),"§bGemeldeter Spieler: §f"+report.reportedName(),List.of("§7UUID: §f"+report.reportedUuid())));inv.setItem(24,head(report.reporterUuid(),report.reporterName(),"§bGemeldet von: §f"+report.reporterName(),List.of("§7UUID: §f"+report.reporterUuid())));inv.setItem(31,item(Material.WRITABLE_BOOK,"§eGrund",wrap(report.reason())));inv.setItem(33,item(Material.REDSTONE,"§cGrimAC-Flags",wrap(report.grimFlags())));Duration[] bans={Duration.ofHours(1),Duration.ofDays(1),Duration.ofDays(7),Duration.ofDays(30)};Duration[] mutes={Duration.ofMinutes(30),Duration.ofHours(6),Duration.ofDays(1),Duration.ofDays(7)};if(player.hasPermission("reports.tempban"))inv.setItem(36,item(Material.CLOCK,"§6Temporär bannen",List.of("§7Dauer: §f"+format(bans[banIndex]),"§eLinksklick: bannen","§eRechtsklick: Dauer ändern")));if(player.hasPermission("reports.ban"))inv.setItem(37,item(Material.BEDROCK,"§4Permanent bannen",List.of("§cSofortiger Kick")));if(player.hasPermission("reports.tempmute"))inv.setItem(38,item(Material.ORANGE_DYE,"§6Temporär muten",List.of("§7Dauer: §f"+format(mutes[muteIndex]),"§eLinksklick: muten","§eRechtsklick: Dauer ändern")));if(player.hasPermission("reports.mute"))inv.setItem(39,item(Material.BLACK_DYE,"§4Permanent muten",List.of()));if(player.hasPermission("reports.unban"))inv.setItem(40,item(Material.MILK_BUCKET,"§aSanktionen aufheben",List.of("§7Ban und Mute entfernen")));if(player.hasPermission("reports.manage")){inv.setItem(45,item(Material.LIME_DYE,"§aOffen",List.of("§7Status setzen")));inv.setItem(46,item(Material.YELLOW_DYE,"§eIn Bearbeitung",List.of("§7Status setzen")));inv.setItem(47,item(Material.LIGHT_BLUE_DYE,"§bGelöst",List.of("§7Status setzen")));inv.setItem(48,item(Material.GRAY_DYE,"§8Abgelehnt",List.of("§7Status setzen")));}inv.setItem(49,item(Material.ARROW,"§eZur Übersicht",List.of()));player.openInventory(inv);}
 private String format(Duration value){return value.toDays()>0?value.toDays()+" Tage":value.toHours()>0?value.toHours()+" Stunden":value.toMinutes()+" Minuten";}
 private ReportStatus next(ReportStatus current){if(current==null)return ReportStatus.OPEN;ReportStatus[] all=ReportStatus.values();return current==all[all.length-1]?null:all[current.ordinal()+1];}
 private Material statusMaterial(ReportStatus status){return switch(status){case OPEN->Material.RED_WOOL;case REVIEWING->Material.YELLOW_WOOL;case RESOLVED->Material.LIME_WOOL;case REJECTED->Material.GRAY_WOOL;};}
 private String statusColor(ReportStatus status){return switch(status){case OPEN->"§c";case REVIEWING->"§e";case RESOLVED->"§a";case REJECTED->"§8";};}
 private List<String> wrap(String value){if(value==null||value.isBlank())return List.of("§7Nicht verfügbar");List<String> lines=new ArrayList<>();for(int i=0;i<value.length();i+=42)lines.add("§f"+value.substring(i,Math.min(value.length(),i+42)));return lines;}
 private ItemStack item(Material material,String name,List<String> lore){ItemStack stack=new ItemStack(material);ItemMeta meta=stack.getItemMeta();meta.displayName(Component.text(name));meta.lore(lore.stream().map(Component::text).toList());stack.setItemMeta(meta);return stack;}
 private ItemStack head(UUID uuid,String playerName,String name,List<String> lore){ItemStack stack=new ItemStack(Material.PLAYER_HEAD);org.bukkit.inventory.meta.SkullMeta meta=(org.bukkit.inventory.meta.SkullMeta)stack.getItemMeta();meta.setOwningPlayer(Bukkit.getOfflinePlayer(uuid));meta.displayName(Component.text(name));meta.lore(lore.stream().map(Component::text).toList());stack.setItemMeta(meta);return stack;}
}
